// The agents extension, installed by this one.
//
// This product cannot hold a conversation without it. The agent pod, the tmux pane behind every
// conversation, the terminal component the pages embed and the seed of scripts each workspace
// copies all belong to the agents extension - so a Dev product on a Rancher without it draws
// every page and every "Ask the agent" button fails with a message telling you to go and install
// something else. That is the same coupling Apps Plus had, and it has the same answer:
// installing this extension should be all it takes.
//
// It is not folded in, deliberately. Apps Plus came inside because it is the layer this product
// is built on - Apps, Installations, the render - and nothing else uses it. The agents extension
// is the opposite: it is useful on its own, it has its own drawer and its own conversations that
// have nothing to do with workspaces, and other things are built on it. So it stays a separate
// extension and this installs it.
//
// A Helm dependency would be the tidier packaging, and it is not available: the chart is
// generated by Rancher's shared reusable workflow (build-extension-charts.yml), so adding a
// subchart means forking the pipeline that publishes every version of this. Installing through
// the catalog gets the same end state - a normal, managed, upgradable release that the
// Extensions page lists - without owning a fork of Rancher's build.
import { devFetch, clusterBase } from './api';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Json = any;

const AGENTS = 'agents';
const AGENTS_REPO_URL = 'https://codyrancher.github.io/agents';
/** Where every UI extension is installed; the catalog refuses any other namespace for one. */
const PLUGIN_NAMESPACE = 'cattle-ui-plugin-system';

/** One attempt per page, whatever else asks: a helm install is not a thing to race. */
let asked = false;

function base(): string {
  return clusterBase('local');
}

/** Whether the agents extension is installed, by the one object that proves it loads. */
async function installed(): Promise<boolean> {
  const plugin = await devFetch(`${ base() }/v1/catalog.cattle.io.uiplugins/${ PLUGIN_NAMESPACE }/${ AGENTS }`, { timeoutMs: 8000 })
    .catch(() => null);

  return plugin?.metadata?.name === AGENTS;
}

/** The repository it comes from, created if this Rancher has never had it. */
async function ensureRepo(): Promise<boolean> {
  const url = `${ base() }/v1/catalog.cattle.io.clusterrepos`;
  const existing = await devFetch(`${ url }/${ AGENTS }`, { timeoutMs: 8000 }).catch(() => null);

  if (existing?.metadata?.name === AGENTS) {
    return true;
  }

  const made = await devFetch(url, {
    method: 'POST',
    body:   JSON.stringify({
      apiVersion: 'catalog.cattle.io/v1',
      kind:       'ClusterRepo',
      metadata:   { name: AGENTS },
      spec:       { url: AGENTS_REPO_URL },
    }),
  }).catch(() => null);

  return !!made;
}

/** The newest version the repository offers, or '' while it has not been downloaded yet. */
async function newest(): Promise<string> {
  const index = await devFetch(`${ base() }/v1/catalog.cattle.io.clusterrepos/${ AGENTS }?link=index`, { timeoutMs: 15000 })
    .catch(() => null);
  const entries: Json[] = index?.entries?.[AGENTS] || [];

  return entries[0]?.version || '';
}

/**
 * Install the agents extension if it is not here.
 *
 * Install only, never upgrade: which version of it to run is the person's call, and a product
 * that quietly moved somebody's extension forward on a page load would be a worse citizen than
 * the one that made them install it by hand.
 *
 * Quiet, and once. It needs the rights to install a chart, which is an administrator; for anyone
 * else the conversation pages say what is missing, in the one place they already said it. A
 * Rancher that has just had the repository created has nothing in its index for a few seconds,
 * so this gives up and the next page load tries again.
 */
export async function ensureAgentsExtension(): Promise<void> {
  if (asked) {
    return;
  }
  asked = true;

  if (await installed()) {
    return;
  }

  if (!await ensureRepo()) {
    return;
  }

  const version = await newest();

  if (!version) {
    // The repository is there but its index is not downloaded yet. Nothing to do but come back.
    asked = false;

    return;
  }

  const body = {
    charts: [{
      chartName:   AGENTS,
      version,
      releaseName: AGENTS,
      annotations: {
        'catalog.cattle.io/ui-source-repo':      AGENTS,
        'catalog.cattle.io/ui-source-repo-type': 'cluster',
      },
      values: {},
    }],
    namespace: PLUGIN_NAMESPACE,
    wait:      true,
    timeout:   '600s',
  };

  const done = await devFetch(`${ base() }/v1/catalog.cattle.io.clusterrepos/${ AGENTS }?action=install`, {
    method:   'POST',
    body:     JSON.stringify(body),
    timeoutMs: 300000,
  }).catch((e: Json) => {
    console.info(`[dev] the agents extension could not be installed automatically (${ e?.message || e }). Conversations need it; install it from Extensions.`); // eslint-disable-line no-console

    return null;
  });

  if (done) {
    // Said out loud: this installed something on somebody's cluster, which is not a thing to do
    // silently even when it is the right thing to do.
    console.info(`[dev] installed the agents extension ${ version }, which this product needs to hold conversations. Reload to pick it up.`); // eslint-disable-line no-console
  }
}
