annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/rancher-version: '>= 2.10.0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
  catalog.cattle.io/display-name: Dev Extension
apiVersion: v2
appVersion: 0.3.20
description: >-
  Workspaces for rancher/dashboard pointed at any Rancher, with reviews, fixes,
  shares and agents
name: dev-extension
type: application
version: 0.3.20
icon: https://codyrancher.github.io/dev-extension/icon.svg
