// Pack pkg/dev-extension/dev-api/server.mjs into dev-api.generated.ts, so the in-cluster API is
// written as a file - with a syntax check and no escaping - and shipped as the string the
// ConfigMap needs. `node scripts/gen-dev-api.mjs`; the output is committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, '..', 'pkg', 'dev-extension', 'dev-api', 'server.mjs');
const OUT = path.join(here, '..', 'pkg', 'dev-extension', 'dev-api.generated.ts');

fs.writeFileSync(OUT, `// Generated by scripts/gen-dev-api.mjs from pkg/dev-extension/dev-api/server.mjs. Do not edit.
/* eslint-disable */
export const DEV_API_SERVER = ${ JSON.stringify(fs.readFileSync(SRC, 'utf8')) };
`);
console.log(`dev-api: ${ fs.statSync(SRC).size } bytes -> ${ path.relative(process.cwd(), OUT) }`);
