// Pack pkg/dev-extension/certs/control.mjs into certs.generated.ts, so the certificate
// controller is written as a file - with a syntax check and no escaping - and shipped as the
// string its ConfigMap needs. `node scripts/gen-certs.mjs`; the output is committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, '..', 'pkg', 'dev-extension', 'certs', 'control.mjs');
const OUT = path.join(here, '..', 'pkg', 'dev-extension', 'certs.generated.ts');

fs.writeFileSync(OUT, `// Generated by scripts/gen-certs.mjs from pkg/dev-extension/certs/control.mjs. Do not edit.
/* eslint-disable */
export const CERT_CONTROL = ${ JSON.stringify(fs.readFileSync(SRC, 'utf8')) };
`);
console.log(`certs: ${ fs.statSync(SRC).size } bytes -> ${ path.relative(process.cwd(), OUT) }`);
