// Pack cards/ into pkg/dev-extension/cards.generated.ts.
//
// A card is a module (see components/focus/card-api.ts), and a module is evaluated from its source
// at runtime. The nineteen cards this extension ships therefore need to reach the browser as
// *text*, not as imports: evaluated through the same `evalModule` as a card held in a ConfigMap,
// so a bundled card and an edited one are the same kind of thing and there is one code path rather
// than two.
//
//   node scripts/gen-cards.mjs
//
// The generated file is committed, so ordinary builds never run this. Same arrangement, and for
// the same reason, as scripts/gen-agent-seed.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(here, '..', 'cards');
const OUT = path.join(here, '..', 'pkg', 'dev-extension', 'cards.generated.ts');

const files = fs.readdirSync(ROOT).filter((name) => name.endsWith('.js')).sort();
const entries = files.map((name) => {
  const id = name.replace(/\.js$/, '');
  const source = fs.readFileSync(path.join(ROOT, name), 'utf8');
  const declared = /\bid\s*:\s*['"]([^'"]+)['"]/.exec(source);

  if (!declared) {
    throw new Error(`${ name }: no \`id\` in the module. A card is found by its id.`);
  }
  if (declared[1] !== id) {
    // Caught here rather than at runtime: the file name is what the ConfigMap is named after
    // (`dev-card-<id>`), and the id inside is what the deck matches on. If they disagree, a card
    // cannot be overridden and nothing says so.
    throw new Error(`${ name }: declares id '${ declared[1] }', so the file should be ${ declared[1] }.js`);
  }

  return { id, source };
});

const body = entries.map(({ id, source }) => `  ${ JSON.stringify(id) }: ${ JSON.stringify(source) },`).join('\n');

fs.writeFileSync(OUT, `/* eslint-disable */
// Generated by scripts/gen-cards.mjs from cards/. Do not edit: edit the card and run the script.
//
// The source of every card this extension ships, as text. See that script for why these are text
// rather than imports.

/** Every bundled card, by id, as the source of its module. */
export const CARD_SOURCES: Record<string, string> = {
${ body }
};
`);

console.log(`cards.generated.ts: ${ entries.length } cards, ${ (fs.statSync(OUT).size / 1024).toFixed(0) }KB`);
